const designTokens = {
  colors: {
    ink: "#17233c",
    text: "#34405c",
    muted: "#667085",
    black: "#0b1736",
    night: "#17233c",
    panel: "#ffffff",
    panelStrong: "#ffffff",
    border: "#d9dee8",
    borderBright: "#2a5bd7",
    blue: "#2a5bd7",
    blueHot: "#1741a6",
    green: "#008a5b",
    yellow: "#f5b700",
    orange: "#ff5b22",
    orangeHot: "#e54810",
    white: "#ffffff",
    ice: "#f7f9fc",
    cyan: "#2a5bd7",
    success: "#008a5b",
    danger: "#d92d20",
  },
  shadows: {
    blueGlow: "0 12px 28px rgba(42, 91, 215, 0.16)",
    panel: "0 18px 50px rgba(23, 35, 60, 0.10)",
    lift: "0 16px 42px rgba(23, 35, 60, 0.12)",
  },
};

const darkModeStyles = {
  page: {
    background:
      "radial-gradient(circle at 10% 8%, rgba(37, 99, 235, 0.30), transparent 30%), radial-gradient(circle at 88% 16%, rgba(16, 185, 129, 0.18), transparent 28%), radial-gradient(circle at 72% 86%, rgba(245, 197, 66, 0.10), transparent 30%), linear-gradient(155deg, #05070b 0%, #101827 48%, #05070b 100%)",
  },
  backgroundGrid: {
    opacity: 0.52,
  },
  backgroundGlowTop: {
    background: "rgba(37, 99, 235, 0.22)",
  },
  backgroundGlowBottom: {
    background: "rgba(16, 185, 129, 0.14)",
  },
  headerBar: {
    background:
      "linear-gradient(135deg, rgba(8, 13, 22, 0.94), rgba(5, 7, 11, 0.88))",
    border: "1px solid rgba(148, 163, 184, 0.22)",
  },
  commandCard: {
    background:
      "linear-gradient(145deg, rgba(8, 13, 22, 0.88), rgba(5, 7, 11, 0.80))",
    border: "1px solid rgba(148, 163, 184, 0.18)",
  },
  sidebarCard: {
    background: "rgba(5, 7, 11, 0.26)",
    border: "1px solid rgba(148, 163, 184, 0.14)",
  },
  builderCard: {
    background:
      "linear-gradient(155deg, rgba(8, 13, 22, 0.94), rgba(5, 7, 11, 0.90))",
    border: "1px solid rgba(37, 99, 235, 0.48)",
  },
  panelCard: {
    background:
      "linear-gradient(150deg, rgba(8, 13, 22, 0.88), rgba(5, 7, 11, 0.80))",
    border: "1px solid rgba(148, 163, 184, 0.16)",
  },
  subscriptionCard: {
    borderLeft: "4px solid #2563eb",
  },
  metricCard: {
    background:
      "linear-gradient(145deg, rgba(8, 13, 22, 0.88), rgba(5, 7, 11, 0.82))",
    border: "1px solid rgba(148, 163, 184, 0.16)",
  },
  compactPlanCard: {
    borderLeft: "4px solid #f5c542",
  },
  docsQuickPanel: {
    borderLeft: "4px solid #10b981",
  },
  billingButton: {
    background: "#f5c542",
    color: "#05070b",
    borderColor: "rgba(245, 197, 66, 0.55)",
  },
  docsButton: {
    background: "#10b981",
    color: "#03120d",
    borderColor: "rgba(16, 185, 129, 0.55)",
  },
  themeButton: {
    background: "rgba(37, 99, 235, 0.18)",
    color: "#dbeafe",
    borderColor: "rgba(37, 99, 235, 0.42)",
  },
};

const lightModeStyles = {
  page: {
    background: "#f7f9fc",
    color: designTokens.colors.ink,
  },
  backgroundGrid: {
    opacity: 0,
  },
  backgroundGlowTop: {
    background: "transparent",
  },
  backgroundGlowBottom: {
    background: "transparent",
  },
  headerBar: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: designTokens.shadows.panel,
  },
  commandCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.ink,
  },
  sidebarCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
  },
  builderCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: designTokens.shadows.panel,
  },
  panelCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.ink,
  },
  subscriptionCard: {
    background: "#eef3ff",
    border: "1px solid #c9d7fb",
    borderLeft: `4px solid ${designTokens.colors.blue}`,
    color: designTokens.colors.ink,
  },
  metricCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.ink,
  },
  compactPlanCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderLeft: `4px solid ${designTokens.colors.blue}`,
    color: designTokens.colors.ink,
  },
  docsQuickPanel: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderLeft: `4px solid ${designTokens.colors.green}`,
    color: designTokens.colors.ink,
  },
  billingButton: {
    background: "#ffffff",
    color: designTokens.colors.blue,
    borderColor: designTokens.colors.border,
  },
  docsButton: {
    background: "#ffffff",
    color: designTokens.colors.blue,
    borderColor: designTokens.colors.border,
  },
  themeButton: {
    background: designTokens.colors.blue,
    color: "#ffffff",
    borderColor: designTokens.colors.blue,
  },
};

const styles = {
  page: {
    minHeight: "100vh",
    position: "relative",
    overflowX: "clip",
    background: "#f7f9fc",
    color: designTokens.colors.ink,
    padding: "20px 18px 44px",
    fontFamily:
      "'Inter Tight', Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  backgroundGrid: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    opacity: 0,
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -160,
    left: "8%",
    width: 420,
    height: 420,
    background: "transparent",
    filter: "blur(86px)",
    pointerEvents: "none",
  },
  backgroundGlowBottom: {
    position: "absolute",
    right: "-7%",
    bottom: "-12%",
    width: 520,
    height: 520,
    background: "transparent",
    filter: "blur(104px)",
    pointerEvents: "none",
  },
  publicShell: {
    position: "relative",
    zIndex: 1,
    maxWidth: 1260,
    margin: "0 auto",
    display: "grid",
    gap: 34,
  },
  publicNav: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 18,
    flexWrap: "wrap",
    padding: "10px 0 18px",
  },
  brandLink: {
    display: "inline-flex",
    alignItems: "center",
    textDecoration: "none",
  },
  navLogo: {
    width: 184,
    height: 46,
  },
  publicNavLinks: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    padding: 4,
    borderRadius: 8,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: "0 10px 28px rgba(23, 35, 60, 0.06)",
  },
  publicNavLink: {
    padding: "9px 13px",
    borderRadius: 6,
    color: designTokens.colors.ink,
    textDecoration: "none",
    fontSize: 14,
    fontWeight: 700,
    transition: "background 180ms ease, color 180ms ease, transform 180ms ease",
  },
  publicNavLinkActive: {
    color: designTokens.colors.white,
    background: designTokens.colors.blue,
    boxShadow: "none",
  },
  publicContentGrid: {
    display: "grid",
    gap: 24,
    alignItems: "start",
  },
  authShell: {
    position: "relative",
    zIndex: 1,
    maxWidth: 1180,
    margin: "0 auto",
    display: "grid",
    gap: 24,
    alignItems: "start",
  },
  dashboardShell: {
    position: "relative",
    zIndex: 1,
    maxWidth: 1440,
    margin: "0 auto",
    display: "grid",
    gap: 22,
  },
  loadingShell: {
    position: "relative",
    zIndex: 1,
    maxWidth: 640,
    margin: "12vh auto 0",
    padding: 32,
    borderRadius: 30,
    background: designTokens.colors.panelStrong,
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: designTokens.shadows.panel,
    textAlign: "center",
  },
  loadingLogo: {
    margin: "0 auto 16px",
  },
  loadingTitle: {
    margin: 0,
    fontSize: "2.2rem",
  },
  loadingText: {
    margin: "12px 0 0",
    color: "#cbd5e1",
  },
  heroPanel: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 24,
    alignItems: "center",
    paddingTop: 8,
  },
  homeStack: {
    display: "grid",
    gap: 18,
  },
  heroCopy: {
    display: "grid",
    gap: 18,
    minWidth: 0,
  },
  heroLogo: {
    width: "min(430px, 88vw)",
    height: "auto",
    filter: "drop-shadow(0 0 34px rgba(76, 85, 255, 0.16))",
  },
  title: {
    margin: "4px 0",
    fontSize: "clamp(2.8rem, 5vw, 5.6rem)",
    lineHeight: 0.94,
    letterSpacing: 0,
    maxWidth: 760,
    color: designTokens.colors.ink,
    textShadow: "none",
  },
  subtitle: {
    margin: 0,
    maxWidth: 610,
    fontSize: "clamp(1rem, 1.5vw, 1.22rem)",
    lineHeight: 1.65,
    color: designTokens.colors.text,
  },
  heroActions: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },
  secondaryLinkButton: {
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 8,
    padding: "15px 18px",
    fontSize: 15,
    fontWeight: 800,
    background: "#ffffff",
    color: designTokens.colors.blue,
    cursor: "pointer",
    textDecoration: "none",
    boxShadow: "0 10px 24px rgba(23, 35, 60, 0.06)",
  },
  compactFeatureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 12,
  },
  compactFeatureCard: {
    padding: "14px 16px",
    borderRadius: 8,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.ink,
    fontWeight: 800,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  publicPageCard: {
    display: "grid",
    gap: 20,
    padding: "clamp(22px, 4vw, 42px)",
    borderRadius: 12,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: designTokens.shadows.panel,
  },
  publicTitle: {
    margin: 0,
    fontSize: "clamp(2.35rem, 5vw, 5rem)",
    lineHeight: 0.94,
    letterSpacing: 0,
    color: designTokens.colors.ink,
  },
  publicLead: {
    margin: 0,
    maxWidth: 720,
    color: designTokens.colors.text,
    lineHeight: 1.7,
    fontSize: "1.04rem",
  },
  publicSectionTitle: {
    margin: "8px 0 10px",
    fontSize: "clamp(1.35rem, 2.3vw, 2.1rem)",
    lineHeight: 1,
    letterSpacing: "-0.04em",
    color: designTokens.colors.white,
  },
  docGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  docCard: {
    display: "grid",
    gap: 8,
    padding: 18,
    borderRadius: 22,
    background: "rgba(3, 4, 10, 0.58)",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  docTitle: {
    margin: 0,
    fontSize: "1rem",
  },
  transmissionCard: {
    position: "relative",
    overflow: "hidden",
    minHeight: 372,
    padding: 22,
    borderRadius: 12,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: designTokens.shadows.panel,
  },
  shortenerPreviewCard: {
    display: "grid",
    gap: 18,
    padding: 22,
    borderRadius: 12,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: designTokens.shadows.panel,
  },
  previewHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  previewDomain: {
    color: designTokens.colors.blue,
    fontWeight: 900,
    fontSize: 14,
  },
  previewForm: {
    display: "grid",
    gap: 12,
    padding: 16,
    borderRadius: 8,
    background: "#f7f9fc",
    border: `1px solid ${designTokens.colors.border}`,
  },
  previewLabel: {
    display: "grid",
    gap: 8,
    color: designTokens.colors.ink,
    fontSize: 13,
    fontWeight: 800,
  },
  previewInput: {
    minHeight: 46,
    display: "flex",
    alignItems: "center",
    padding: "12px 14px",
    borderRadius: 8,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.text,
    wordBreak: "break-all",
  },
  previewAliasRow: {
    minHeight: 46,
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: "12px 14px",
    borderRadius: 8,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.text,
  },
  previewButton: {
    border: "none",
    borderRadius: 8,
    minHeight: 48,
    background: designTokens.colors.blue,
    color: "#ffffff",
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: "0 12px 24px rgba(255, 91, 34, 0.22)",
  },
  previewResultGrid: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    gap: 16,
    alignItems: "center",
  },
  previewQr: {
    padding: 10,
    borderRadius: 8,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
  },
  previewShortLink: {
    margin: "4px 0 12px",
    color: designTokens.colors.blue,
    fontSize: "1.25rem",
    fontWeight: 950,
    wordBreak: "break-all",
  },
  previewMiniButton: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 32,
    padding: "7px 10px",
    borderRadius: 8,
    background: "#eef3ff",
    color: designTokens.colors.blue,
    fontSize: 12,
    fontWeight: 900,
  },
  visualHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    position: "relative",
    zIndex: 1,
  },
  visualDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    background: designTokens.colors.blue,
    boxShadow: "0 0 22px rgba(76, 85, 255, 0.9)",
  },
  visualLabel: {
    flex: 1,
    color: designTokens.colors.text,
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  routeCanvas: {
    position: "relative",
    height: 220,
    margin: "28px 0 22px",
    borderRadius: 12,
    background:
      "linear-gradient(180deg, #f7f9fc, #ffffff), linear-gradient(90deg, rgba(42,91,215,0.08) 1px, transparent 1px), linear-gradient(0deg, rgba(42,91,215,0.08) 1px, transparent 1px)",
    backgroundSize: "auto, 34px 34px, 34px 34px",
    border: `1px solid ${designTokens.colors.border}`,
    overflow: "hidden",
  },
  routeNode: {
    position: "absolute",
    zIndex: 2,
    width: 68,
    height: 68,
    display: "grid",
    placeItems: "center",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: "0.08em",
    color: designTokens.colors.white,
    background: designTokens.colors.blue,
    border: `1px solid ${designTokens.colors.blue}`,
    boxShadow: designTokens.shadows.blueGlow,
  },
  routeNodeSource: {
    left: 24,
    top: 76,
  },
  routeNodeEdge: {
    left: "calc(50% - 34px)",
    top: 26,
    background: "linear-gradient(135deg, rgba(76, 85, 255, 0.95), rgba(9, 12, 28, 0.92))",
  },
  routeNodeTarget: {
    right: 24,
    bottom: 34,
  },
  latencyGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    position: "relative",
    zIndex: 1,
  },
  latencyCard: {
    display: "grid",
    gap: 4,
    padding: 14,
    borderRadius: 18,
    background: "rgba(255, 255, 255, 0.045)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
  },
  latencyValue: {
    color: designTokens.colors.white,
    fontSize: "1.55rem",
    fontWeight: 950,
    letterSpacing: "-0.04em",
  },
  latencyLabel: {
    color: designTokens.colors.muted,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  metricStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 12,
  },
  metricStripCard: {
    display: "grid",
    gap: 8,
    padding: 18,
    borderRadius: 14,
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
    boxShadow: designTokens.shadows.panel,
  },
  metricStripValue: {
    color: "var(--sl-heading)",
    fontSize: "1.8rem",
    lineHeight: 1,
    letterSpacing: "-0.05em",
  },
  showcaseGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  showcaseCard: {
    display: "grid",
    gap: 12,
    padding: 20,
    borderRadius: 16,
    minHeight: 190,
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
    boxShadow: designTokens.shadows.panel,
  },
  signalBadge: {
    width: "fit-content",
    padding: "7px 10px",
    borderRadius: 999,
    background: "rgba(42, 91, 215, 0.10)",
    color: designTokens.colors.blue,
    border: "1px solid rgba(42, 91, 215, 0.22)",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  showcaseTitle: {
    margin: 0,
    color: "var(--sl-heading)",
    fontSize: "1.25rem",
    letterSpacing: "-0.035em",
  },
  analyticsPreviewCard: {
    display: "grid",
    gap: 18,
    padding: 22,
    borderRadius: 16,
    background: "linear-gradient(135deg, #eef3ff, #ffffff)",
    border: "1px solid rgba(42, 91, 215, 0.24)",
    boxShadow: designTokens.shadows.panel,
  },
  chartPreview: {
    height: 160,
    display: "flex",
    gap: 8,
    alignItems: "end",
    padding: 16,
    borderRadius: 22,
    background: "rgba(3, 4, 10, 0.54)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
  },
  chartBar: {
    flex: 1,
    minWidth: 8,
    borderRadius: "999px 999px 6px 6px",
    background: "linear-gradient(180deg, #ffffff 0%, #4c55ff 52%, #151cff 100%)",
    boxShadow: "0 0 20px rgba(76, 85, 255, 0.32)",
  },
  apiPreviewCard: {
    display: "grid",
    gap: 16,
    padding: 22,
    borderRadius: 16,
    background: "rgba(5, 7, 16, 0.82)",
    border: `1px solid ${designTokens.colors.border}`,
  },
  codePanel: {
    display: "grid",
    gap: 6,
    padding: 18,
    borderRadius: 22,
    background: "rgba(0, 0, 0, 0.42)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    overflowX: "auto",
  },
  codeRow: {
    display: "block",
    color: designTokens.colors.ice,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    fontSize: 13,
    lineHeight: 1.6,
    whiteSpace: "pre",
  },
  trustGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
  },
  trustPill: {
    padding: "10px 13px",
    borderRadius: 999,
    color: designTokens.colors.text,
    background: "rgba(255, 255, 255, 0.045)",
    border: `1px solid ${designTokens.colors.border}`,
    fontSize: 13,
    fontWeight: 800,
  },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  featureCard: {
    padding: 18,
    borderRadius: 20,
    background: "rgba(15, 23, 42, 0.76)",
    border: "1px solid rgba(148, 163, 184, 0.12)",
  },
  featureTitle: {
    margin: "0 0 8px",
    fontSize: "1rem",
  },
  featureText: {
    margin: 0,
    color: "#cbd5e1",
    lineHeight: 1.6,
  },
  pricingPreview: {
    display: "grid",
    gap: 16,
    padding: 22,
    borderRadius: 24,
    background: "rgba(15, 23, 42, 0.76)",
    border: "1px solid rgba(148, 163, 184, 0.12)",
  },
  authCard: {
    position: "sticky",
    top: 22,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: designTokens.shadows.panel,
  },
  authTabs: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    borderBottom: `1px solid ${designTokens.colors.border}`,
  },
  authTab: {
    border: "none",
    background: "transparent",
    color: designTokens.colors.text,
    padding: "16px 18px",
    fontWeight: 700,
    cursor: "pointer",
  },
  authTabActive: {
    border: "none",
    background: "#eef3ff",
    color: designTokens.colors.blue,
    padding: "16px 18px",
    fontWeight: 800,
    cursor: "pointer",
  },
  authBody: {
    display: "grid",
    gap: 16,
    padding: 24,
  },
  authLogo: {
    width: 62,
    height: 62,
  },
  authTitle: {
    margin: 0,
    fontSize: "1.7rem",
    letterSpacing: "-0.04em",
  },
  authSubtitle: {
    margin: "4px 0 4px",
    color: designTokens.colors.text,
    lineHeight: 1.6,
  },
  headerBar: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "flex-start",
    flexWrap: "wrap",
    padding: 18,
    borderRadius: 12,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  dashboardBrandBlock: {
    display: "flex",
    gap: 14,
    alignItems: "center",
    minWidth: 0,
  },
  dashboardLogo: {
    width: 58,
    height: 58,
    flex: "0 0 auto",
  },
  dashboardTitle: {
    margin: "8px 0 0",
    fontSize: "clamp(1.8rem, 3vw, 3.2rem)",
    lineHeight: 0.96,
    letterSpacing: 0,
    color: designTokens.colors.ink,
  },
  workspaceMeta: {
    margin: "8px 0 0",
    color: designTokens.colors.text,
  },
  headerActions: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
    flex: "1 1 460px",
    justifyContent: "flex-end",
    minWidth: 0,
  },
  navActionButton: {
    border: "1px solid transparent",
    borderRadius: 8,
    padding: "10px 14px",
    minHeight: 42,
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.35)",
    transition: "transform 180ms ease, filter 180ms ease, box-shadow 180ms ease",
  },
  dashboardGrid: {
    display: "grid",
    gap: 20,
    alignItems: "start",
  },
  dashboardNavCard: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: 6,
    borderRadius: 12,
    overflowX: "auto",
    position: "sticky",
    top: 8,
    zIndex: 6,
    boxShadow: designTokens.shadows.panel,
  },
  dashboardNavItem: {
    border: "none",
    borderRadius: 8,
    padding: "10px 14px",
    background: "transparent",
    color: designTokens.colors.blue,
    fontSize: 14,
    fontWeight: 850,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  linkBuilderForm: {
    display: "grid",
    gap: 18,
  },
  builderFormGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  analyticsDetailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 18,
  },
  billingOverviewGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 14,
  },
  billingDetailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 14,
  },
  commandStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  commandCard: {
    display: "grid",
    gap: 8,
    padding: 18,
    borderRadius: 8,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  commandValue: {
    color: designTokens.colors.ink,
    fontSize: "1.65rem",
    lineHeight: 1,
    letterSpacing: 0,
  },
  sidebarCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 12,
    padding: 20,
    display: "grid",
    gap: 16,
  },
  builderCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 12,
    padding: 22,
    display: "grid",
    gap: 18,
    boxShadow: designTokens.shadows.panel,
  },
  analyticsPanel: {
    display: "grid",
    gap: 18,
    alignContent: "start",
  },
  analyticsHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  sectionEyebrow: {
    margin: 0,
    fontSize: 12,
    letterSpacing: 0,
    textTransform: "uppercase",
    color: designTokens.colors.blue,
    fontWeight: 900,
  },
  panelTitle: {
    margin: "6px 0 0",
    fontSize: "1.15rem",
    letterSpacing: 0,
    color: designTokens.colors.ink,
  },
  panelTitleRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  label: {
    display: "grid",
    gap: 10,
    fontSize: 14,
    fontWeight: 700,
    color: designTokens.colors.ink,
  },
  input: {
    width: "100%",
    borderRadius: 8,
    border: `1px solid ${designTokens.colors.border}`,
    background: "#ffffff",
    color: designTokens.colors.ink,
    padding: "15px 16px",
    outline: "none",
    fontSize: 15,
    transition: "border-color 180ms ease, box-shadow 180ms ease, background 180ms ease",
  },
  aliasInputGroup: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    alignItems: "stretch",
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 8,
    overflow: "hidden",
    background: "#ffffff",
  },
  aliasPrefix: {
    display: "flex",
    alignItems: "center",
    padding: "0 14px",
    background: "#eef3ff",
    color: designTokens.colors.blue,
    borderRight: `1px solid ${designTokens.colors.border}`,
    fontWeight: 900,
    fontSize: 14,
    whiteSpace: "nowrap",
  },
  aliasInput: {
    border: "none",
    borderRadius: 0,
    boxShadow: "none",
  },
  textarea: {
    width: "100%",
    minHeight: 110,
    resize: "vertical",
    borderRadius: 8,
    border: `1px solid ${designTokens.colors.border}`,
    background: "#ffffff",
    color: designTokens.colors.ink,
    padding: "15px 16px",
    outline: "none",
    fontSize: 15,
    fontFamily: "inherit",
    transition: "border-color 180ms ease, box-shadow 180ms ease, background 180ms ease",
  },
  select: {
    width: "100%",
    borderRadius: 8,
    border: `1px solid ${designTokens.colors.border}`,
    background: "#ffffff",
    color: designTokens.colors.ink,
    padding: "15px 16px",
    outline: "none",
    fontSize: 15,
  },
  primaryButton: {
    border: "none",
    borderRadius: 8,
    padding: "15px 18px",
    fontSize: 15,
    fontWeight: 900,
    letterSpacing: 0,
    background: designTokens.colors.blue,
    color: "#ffffff",
    cursor: "pointer",
    boxShadow: "0 12px 24px rgba(42, 91, 215, 0.22)",
    transition: "transform 180ms ease, box-shadow 180ms ease, filter 180ms ease",
  },
  secondaryButton: {
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 14,
    fontWeight: 800,
    background: "#ffffff",
    color: designTokens.colors.blue,
    cursor: "pointer",
    transition: "transform 180ms ease, border-color 180ms ease, background 180ms ease",
  },
  dangerButton: {
    border: "none",
    borderRadius: 8,
    padding: "14px 18px",
    fontSize: 15,
    fontWeight: 800,
    background: designTokens.colors.danger,
    color: "#fff7ed",
    cursor: "pointer",
  },
  feedback: {
    margin: 0,
    padding: "12px 14px",
    borderRadius: 8,
    lineHeight: 1.5,
    fontSize: 14,
    fontWeight: 700,
  },
  feedbackError: {
    color: "#912018",
    background: "#fee4e2",
    border: "1px solid #fecdca",
  },
  feedbackSuccess: {
    color: "#05603a",
    background: "#dcf8ee",
    border: "1px solid #a6f4d0",
  },
  helperText: {
    margin: 0,
    color: designTokens.colors.text,
    lineHeight: 1.6,
  },
  miniHelperText: {
    margin: "6px 0 0",
    color: designTokens.colors.muted,
    fontSize: 12,
    lineHeight: 1.4,
  },
  legalCard: {
    display: "grid",
    gap: 16,
    padding: 22,
    borderRadius: 24,
    background: "rgba(6, 78, 59, 0.24)",
    border: "1px solid rgba(45, 212, 191, 0.18)",
  },
  legalList: {
    display: "grid",
    gap: 10,
  },
  legalNoticeItem: {
    margin: 0,
    color: "#d1fae5",
    lineHeight: 1.65,
  },
  legalFinePrint: {
    margin: 0,
    color: "#a7f3d0",
    fontSize: 13,
    lineHeight: 1.6,
  },
  legalLinkRow: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap",
  },
  consentBox: {
    display: "grid",
    gap: 12,
    padding: 16,
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  consentIntro: {
    margin: 0,
    color: "var(--sl-content)",
    fontSize: 13,
    lineHeight: 1.6,
  },
  checkboxRow: {
    display: "grid",
    gridTemplateColumns: "20px minmax(0, 1fr)",
    gap: 10,
    alignItems: "start",
    color: "var(--sl-content)",
    fontSize: 13,
    lineHeight: 1.5,
    cursor: "pointer",
  },
  checkboxInput: {
    width: 16,
    height: 16,
    marginTop: 2,
    accentColor: designTokens.colors.blue,
  },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 14,
  },
  metricCard: {
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
    borderRadius: 22,
    padding: 18,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  metricLabel: {
    margin: 0,
    color: designTokens.colors.muted,
    fontSize: 13,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    fontWeight: 800,
  },
  metricValue: {
    margin: "12px 0 0",
    fontSize: "2.2rem",
    fontWeight: 900,
    lineHeight: 1,
    color: "var(--sl-heading)",
  },
  metricValueSmall: {
    margin: "12px 0 0",
    fontSize: "1rem",
    fontWeight: 700,
    lineHeight: 1.5,
  },
  metricHint: {
    color: designTokens.colors.muted,
    fontSize: 13,
  },
  resultCard: {
    display: "grid",
    gap: 18,
    padding: 20,
    borderRadius: 22,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  resultTopRow: {
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  mutedLabel: {
    margin: "0 0 8px",
    fontSize: 12,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: designTokens.colors.muted,
  },
  link: {
    color: designTokens.colors.cyan,
    fontWeight: 700,
    textDecoration: "none",
    wordBreak: "break-all",
  },
  inlineActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  inlineForm: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 10,
    alignItems: "center",
  },
  qrPanel: {
    display: "flex",
    gap: 18,
    alignItems: "center",
    flexWrap: "wrap",
  },
  qrText: {
    flex: 1,
    minWidth: 220,
  },
  qrHeadline: {
    margin: "0 0 6px",
    fontSize: "1.05rem",
    fontWeight: 800,
  },
  qrDescription: {
    margin: "0 0 14px",
    color: "var(--sl-content)",
    lineHeight: 1.6,
  },
  linkList: {
    display: "grid",
    gap: 10,
  },
  linkListItem: {
    border: "1px solid var(--sl-surface-border)",
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    color: designTokens.colors.ink,
    padding: 16,
    textAlign: "left",
    cursor: "pointer",
    transition: "transform 180ms ease, border-color 180ms ease, background 180ms ease",
  },
  linkListItemActive: {
    border: `1px solid ${designTokens.colors.blue}`,
    borderRadius: 18,
    background: "var(--sl-surface-accent)",
    color: designTokens.colors.ink,
    padding: 16,
    textAlign: "left",
    cursor: "pointer",
    boxShadow: designTokens.shadows.blueGlow,
  },
  linkListTopRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
  },
  linkShortCode: {
    fontWeight: 800,
    fontSize: 15,
    letterSpacing: "0.03em",
  },
  linkOriginal: {
    margin: "10px 0",
    color: "var(--sl-content)",
    lineHeight: 1.55,
    wordBreak: "break-word",
  },
  linkListFooter: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    color: "var(--sl-muted-content)",
    fontSize: 12,
    flexWrap: "wrap",
  },
  panelCard: {
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
    borderRadius: 26,
    padding: 20,
    display: "grid",
    gap: 16,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  docsQuickPanel: {
    display: "grid",
    gap: 14,
    padding: 18,
    borderRadius: 22,
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
  },
  docsQuickList: {
    display: "grid",
    gap: 10,
  },
  docsQuickItem: {
    display: "grid",
    gap: 5,
    padding: 12,
    borderRadius: 14,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
    color: designTokens.colors.text,
    fontSize: 13,
    lineHeight: 1.45,
  },
  subscriptionCard: {
    display: "grid",
    gap: 10,
    padding: 16,
    borderRadius: 18,
    background: "var(--sl-surface-accent)",
    border: "1px solid var(--sl-surface-border)",
  },
  subscriptionTitle: {
    margin: 0,
    color: "var(--sl-heading)",
    fontSize: "1.65rem",
    lineHeight: 1,
    fontWeight: 950,
  },
  billingStatsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
  },
  billingStatCard: {
    padding: 16,
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  billingStatLabel: {
    margin: 0,
    color: designTokens.colors.muted,
    fontSize: 12,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  billingStatValue: {
    margin: "10px 0 0",
    fontSize: "1.35rem",
    fontWeight: 800,
    lineHeight: 1.2,
  },
  billingStatValueSmall: {
    margin: "10px 0 0",
    fontSize: "0.95rem",
    fontWeight: 700,
    lineHeight: 1.5,
  },
  planGrid: {
    display: "grid",
    gap: 12,
  },
  compactPlanGrid: {
    display: "grid",
    gap: 10,
  },
  planCard: {
    display: "grid",
    gap: 14,
    padding: 18,
    borderRadius: 24,
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
    boxShadow: designTokens.shadows.panel,
  },
  compactPlanCard: {
    display: "grid",
    gap: 10,
    padding: 14,
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  planCardFeatured: {
    border: `1px solid ${designTokens.colors.borderBright}`,
    boxShadow: "0 22px 70px rgba(76, 85, 255, 0.22), inset 0 1px 0 rgba(255, 255, 255, 0.08)",
  },
  planHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  planName: {
    fontSize: "1rem",
  },
  planPrice: {
    margin: 0,
    fontSize: "1.7rem",
    fontWeight: 900,
    lineHeight: 1,
    color: "var(--sl-heading)",
  },
  compactPlanPrice: {
    margin: 0,
    fontSize: "1.25rem",
    fontWeight: 900,
    lineHeight: 1.1,
    color: "var(--sl-heading)",
  },
  planFeatureList: {
    display: "grid",
    gap: 8,
  },
  planFeatureItem: {
    margin: 0,
    color: designTokens.colors.text,
    lineHeight: 1.5,
  },
  paymentCard: {
    display: "grid",
    gap: 8,
    padding: 16,
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  usageGrid: {
    display: "grid",
    gap: 12,
  },
  usageBar: {
    display: "grid",
    gap: 8,
  },
  usageBarHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  usageBarLabel: {
    color: designTokens.colors.text,
    fontSize: 13,
    fontWeight: 800,
  },
  usageBarCount: {
    color: designTokens.colors.muted,
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  usageBarTrack: {
    height: 8,
    borderRadius: 999,
    background: "rgba(148, 163, 184, 0.16)",
    overflow: "hidden",
  },
  usageBarFill: {
    height: "100%",
    borderRadius: 999,
    transition: "width 180ms ease",
  },
  invoiceList: {
    display: "grid",
    gap: 10,
  },
  invoiceRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    padding: 12,
    borderRadius: 14,
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
  },
  inlineLink: {
    color: designTokens.colors.blue,
    fontSize: 13,
    fontWeight: 800,
    textDecoration: "none",
  },
  domainList: {
    display: "grid",
    gap: 12,
  },
  domainCard: {
    display: "grid",
    gap: 12,
    padding: 16,
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  dnsGrid: {
    display: "grid",
    gap: 10,
  },
  codeLine: {
    margin: "4px 0 0",
    padding: "8px 10px",
    borderRadius: 10,
    background: "rgba(0, 0, 0, 0.42)",
    color: designTokens.colors.ice,
    fontFamily: "ui-monospace, SFMono-Regular, Consolas, monospace",
    fontSize: 12,
    lineHeight: 1.5,
    wordBreak: "break-all",
  },
  routeList: {
    display: "grid",
    gap: 12,
  },
  routeCard: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    flexWrap: "wrap",
    padding: 16,
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  routeLabel: {
    margin: "0 0 6px",
    fontSize: 13,
    fontWeight: 800,
    color: "var(--sl-heading)",
    letterSpacing: "0.03em",
    textTransform: "uppercase",
  },
  routeUrl: {
    margin: 0,
    color: "var(--sl-content)",
    wordBreak: "break-all",
  },
  routeMeta: {
    display: "grid",
    gap: 8,
    justifyItems: "end",
  },
  routeTime: {
    fontSize: 12,
    color: "var(--sl-muted-content)",
  },
  deviceBar: {
    display: "grid",
    gap: 8,
  },
  deviceBarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deviceBarLabel: {
    fontWeight: 700,
    textTransform: "capitalize",
  },
  deviceBarCount: {
    color: "var(--sl-content)",
  },
  deviceBarTrack: {
    height: 10,
    borderRadius: 999,
    background: "rgba(100, 116, 139, 0.18)",
    overflow: "hidden",
  },
  deviceBarFill: {
    height: "100%",
    borderRadius: 999,
    background: "linear-gradient(90deg, #ffffff 0%, #4c55ff 70%, #79e6ff 100%)",
    boxShadow: "0 0 18px rgba(76, 85, 255, 0.35)",
  },
  eventList: {
    display: "grid",
    gap: 12,
  },
  eventCard: {
    padding: 16,
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  eventTopRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  eventTitle: {
    fontSize: 15,
  },
  eventMeta: {
    margin: "8px 0 6px",
    color: "var(--sl-content)",
  },
  eventTarget: {
    margin: "0 0 6px",
    color: designTokens.colors.blue,
    wordBreak: "break-all",
  },
  eventReferrer: {
    margin: 0,
    color: "var(--sl-muted-content)",
    wordBreak: "break-word",
  },
  emptyState: {
    margin: 0,
    color: "#cbd5e1",
    lineHeight: 1.6,
  },
};

export { darkModeStyles, designTokens, lightModeStyles, styles };
