const designTokens = {
  colors: {
    ink: "#0f172a",
    text: "#475569",
    muted: "#64748b",
    black: "#0f172a",
    night: "#0f172a",
    panel: "#ffffff",
    panelStrong: "#ffffff",
    border: "#e2e8f0",
    borderBright: "#04775c",
    blue: "#2563eb",
    blueHot: "#1d4ed8",
    green: "#04775c",
    yellow: "#f5b700",
    orange: "#ff5b22",
    orangeHot: "#e54810",
    white: "#ffffff",
    ice: "#f7f9fc",
    cyan: "#2563eb",
    success: "#04775c",
    danger: "#d92d20",
  },
  shadows: {
    blueGlow: "0 12px 28px rgba(37, 99, 235, 0.1)",
    panel: "0 8px 24px rgba(15, 23, 42, 0.05)",
    lift: "0 16px 40px rgba(15, 23, 42, 0.08)",
  },
};

const enterpriseDashboardStyles = {
  page: {
    background: "#f1f4ef",
    color: designTokens.colors.ink,
  },
  backgroundGrid: {
    opacity: 0,
  },
  backgroundGlowTop: {
    background: "transparent",
  },
  backgroundGlowBottom: {
    background: "transparent",
  },
  headerBar: {
    background: "rgba(255, 255, 255, 0.9)",
    border: "1px solid rgba(15, 23, 42, 0.08)",
    boxShadow: "0 18px 55px rgba(15, 23, 42, 0.08)",
  },
  commandCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.ink,
    boxShadow: "none",
  },
  sidebarCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
  },
  builderCard: {
    background: "#ffffff",
    border: "1px solid rgba(15, 23, 42, 0.08)",
    boxShadow: "0 24px 70px rgba(15, 23, 42, 0.08)",
  },
  panelCard: {
    background: "#ffffff",
    border: "1px solid rgba(15, 23, 42, 0.08)",
    color: designTokens.colors.ink,
  },
  subscriptionCard: {
    background: "#ecfdf5",
    border: "1px solid #a7f3d0",
    borderLeft: `4px solid ${designTokens.colors.green}`,
    color: designTokens.colors.ink,
  },
  metricCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.ink,
  },
  compactPlanCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderLeft: `4px solid ${designTokens.colors.green}`,
    color: designTokens.colors.ink,
  },
  docsQuickPanel: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderLeft: `4px solid ${designTokens.colors.green}`,
    color: designTokens.colors.ink,
  },
  billingButton: {
    background: "#ffffff",
    color: designTokens.colors.green,
    borderColor: designTokens.colors.border,
  },
  docsButton: {
    background: "#ffffff",
    color: designTokens.colors.green,
    borderColor: designTokens.colors.border,
  },
};

const styles = {
  page: {
    minHeight: "100vh",
    position: "relative",
    overflowX: "clip",
    background: "#f7f8fb",
    color: designTokens.colors.ink,
    padding: "22px 22px 56px",
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  backgroundGrid: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    opacity: 0,
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -160,
    left: "8%",
    width: 420,
    height: 420,
    background: "transparent",
    filter: "blur(86px)",
    pointerEvents: "none",
  },
  backgroundGlowBottom: {
    position: "absolute",
    right: "-7%",
    bottom: "-12%",
    width: 520,
    height: 520,
    background: "transparent",
    filter: "blur(104px)",
    pointerEvents: "none",
  },
  publicShell: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    display: "grid",
    gap: 0,
  },
  publicPageRoot: {
    padding: 0,
    background: "#ffffff",
    color: "#383738",
    fontFamily:
      "'Plus Jakarta Sans', Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  publicNav: {
    position: "sticky",
    top: 0,
    zIndex: 1000,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 24,
    minHeight: 72,
    padding: "10px max(24px, calc((100vw - 1260px) / 2))",
    background: "rgba(255, 255, 255, 0.85)",
    borderBottom: "1px solid rgba(226, 232, 240, 0.8)",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05), 0 4px 12px rgba(0, 0, 0, 0.03)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  brandLink: {
    display: "inline-flex",
    alignItems: "center",
    textDecoration: "none",
    flexShrink: 0,
  },
  navLogo: {
    width: 174,
    height: 44,
  },
  publicNavLinks: {
    display: "flex",
    gap: 4,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  publicNavLink: {
    padding: "8px 16px",
    borderRadius: 6,
    color: "#475569",
    textDecoration: "none",
    fontSize: 14,
    fontWeight: 500,
    transition: "background 180ms ease, color 180ms ease, transform 180ms ease",
  },
  publicNavLinkActive: {
    color: "#0f172a",
    background: "transparent",
    fontWeight: 600,
    boxShadow: "none",
  },
  publicNavActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  publicSignInButton: {
    minHeight: 34,
    padding: "8px 16px",
    border: "none",
    borderRadius: 6,
    background: "transparent",
    color: "#475569",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
  },
  publicGetStartedButton: {
    minHeight: 40,
    padding: "10px 24px",
    border: "none",
    borderRadius: 10,
    background: "#087f5b",
    color: "#ffffff",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "none",
  },
  publicMain: {
    width: "100%",
  },
  authShell: {
    position: "relative",
    zIndex: 1,
    maxWidth: 1180,
    margin: "0 auto",
    display: "grid",
    gap: 24,
    alignItems: "start",
  },
  dashboardShell: {
    position: "relative",
    zIndex: 1,
    maxWidth: 1480,
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "252px minmax(0, 1fr)",
    gridTemplateRows: "auto auto auto",
    gap: 24,
    alignItems: "start",
  },
  loadingShell: {
    position: "relative",
    zIndex: 1,
    maxWidth: 640,
    margin: "12vh auto 0",
    padding: 32,
    borderRadius: 30,
    background: designTokens.colors.panelStrong,
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: designTokens.shadows.panel,
    textAlign: "center",
  },
  loadingLogo: {
    margin: "0 auto 16px",
  },
  loadingTitle: {
    margin: 0,
    fontSize: "2.2rem",
  },
  loadingText: {
    margin: "12px 0 0",
    color: "#cbd5e1",
  },
  heroPanel: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.08fr) minmax(360px, 0.92fr)",
    gap: 56,
    alignItems: "center",
    width: "min(1260px, calc(100% - 48px))",
    minHeight: 620,
    margin: "0 auto",
    padding: "72px 0",
  },
  homeStack: {
    display: "grid",
    gap: 0,
    width: "100%",
  },
  heroCopy: {
    display: "grid",
    gap: 22,
    minWidth: 0,
  },
  heroLogo: {
    width: "min(430px, 88vw)",
    height: "auto",
    filter: "drop-shadow(0 0 34px rgba(76, 85, 255, 0.16))",
  },
  title: {
    margin: 0,
    fontSize: "clamp(2.75rem, 5vw, 3.5rem)",
    fontWeight: 700,
    lineHeight: 1.1,
    letterSpacing: "-0.025em",
    maxWidth: 680,
    color: "#0f172a",
    textShadow: "none",
  },
  titleAccent: {
    color: "#087f5b",
  },
  subtitle: {
    margin: 0,
    maxWidth: 620,
    fontSize: "clamp(1rem, 1.45vw, 1.18rem)",
    lineHeight: 1.65,
    color: "#475569",
  },
  heroActions: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },
  freePlanBadge: {
    width: "fit-content",
    margin: 0,
    padding: "8px 12px",
    borderRadius: 999,
    color: "#047857",
    background: "#ecfdf5",
    border: "1px solid #a7f3d0",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.02em",
  },
  marketingPrimaryButton: {
    minHeight: 54,
    padding: "0 32px",
    border: "none",
    borderRadius: 10,
    background: "#087f5b",
    color: "#ffffff",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "none",
  },
  marketingSecondaryButton: {
    minHeight: 54,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 32px",
    border: "1px solid #dadada",
    borderRadius: 10,
    background: "#ffffff",
    color: "#1e293b",
    fontSize: 16,
    fontWeight: 600,
    textDecoration: "none",
    boxShadow: "none",
  },
  heroFeatureRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px 20px",
    flexWrap: "wrap",
  },
  heroFeatureItem: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: 650,
  },
  secondaryLinkButton: {
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 10,
    padding: "14px 20px",
    fontSize: 14,
    fontWeight: 600,
    background: "#ffffff",
    color: designTokens.colors.green,
    cursor: "pointer",
    textDecoration: "none",
    boxShadow: "none",
  },
  compactFeatureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 12,
  },
  compactFeatureCard: {
    padding: "14px 16px",
    borderRadius: 8,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    color: designTokens.colors.ink,
    fontWeight: 800,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  publicPageCard: {
    display: "grid",
    gap: 24,
    width: "min(1180px, calc(100% - 48px))",
    margin: "56px auto 88px",
    padding: "clamp(26px, 4vw, 52px)",
    borderRadius: 16,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "none",
  },
  publicTitle: {
    margin: 0,
    maxWidth: 860,
    fontSize: "clamp(2.3rem, 5vw, 3.5rem)",
    fontWeight: 700,
    lineHeight: 1.1,
    letterSpacing: "-0.025em",
    color: "#0f172a",
  },
  publicLead: {
    margin: 0,
    maxWidth: 720,
    color: "#475569",
    lineHeight: 1.7,
    fontSize: "1.08rem",
  },
  publicSectionTitle: {
    margin: "8px 0 10px",
    fontSize: "clamp(1.35rem, 2.3vw, 2.75rem)",
    fontWeight: 700,
    lineHeight: 1.2,
    letterSpacing: "-0.02em",
    color: "#0f172a",
  },
  docGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  docCard: {
    display: "grid",
    gap: 8,
    padding: 20,
    borderRadius: 14,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    boxShadow: "none",
  },
  docTitle: {
    margin: 0,
    fontSize: "1rem",
  },
  transmissionCard: {
    position: "relative",
    overflow: "hidden",
    minHeight: 372,
    padding: 22,
    borderRadius: 12,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    boxShadow: designTokens.shadows.panel,
  },
  shortenerPreviewCard: {
    display: "grid",
    gap: 18,
    padding: 24,
    borderRadius: 18,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "none",
  },
  previewHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  previewDomain: {
    color: designTokens.colors.blue,
    fontWeight: 900,
    fontSize: 14,
  },
  previewForm: {
    display: "grid",
    gap: 12,
    padding: 16,
    borderRadius: 14,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  previewLabel: {
    display: "grid",
    gap: 8,
    color: designTokens.colors.ink,
    fontSize: 13,
    fontWeight: 800,
  },
  previewInput: {
    minHeight: 54,
    display: "flex",
    alignItems: "center",
    padding: "16px 20px",
    borderRadius: 12,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    color: "#475569",
    wordBreak: "break-all",
  },
  previewAliasRow: {
    minHeight: 54,
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: "16px 20px",
    borderRadius: 12,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    color: "#475569",
  },
  previewButton: {
    border: "none",
    borderRadius: 10,
    minHeight: 54,
    background: "#087f5b",
    color: "#ffffff",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "none",
  },
  previewResultGrid: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    gap: 16,
    alignItems: "center",
  },
  previewQr: {
    padding: 10,
    borderRadius: 8,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
  },
  previewShortLink: {
    margin: "4px 0 12px",
    color: designTokens.colors.blue,
    fontSize: "1.25rem",
    fontWeight: 950,
    wordBreak: "break-all",
  },
  previewMiniButton: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 32,
    padding: "7px 10px",
    borderRadius: 8,
    background: "#ecfdf5",
    color: "#047857",
    fontSize: 12,
    fontWeight: 600,
  },
  visualHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    position: "relative",
    zIndex: 1,
  },
  visualDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    background: designTokens.colors.blue,
    boxShadow: "0 0 22px rgba(76, 85, 255, 0.9)",
  },
  visualLabel: {
    flex: 1,
    color: designTokens.colors.text,
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  routeCanvas: {
    position: "relative",
    height: 220,
    margin: "28px 0 22px",
    borderRadius: 12,
    background:
      "linear-gradient(180deg, #f7f9fc, #ffffff), linear-gradient(90deg, rgba(42,91,215,0.08) 1px, transparent 1px), linear-gradient(0deg, rgba(42,91,215,0.08) 1px, transparent 1px)",
    backgroundSize: "auto, 34px 34px, 34px 34px",
    border: `1px solid ${designTokens.colors.border}`,
    overflow: "hidden",
  },
  routeNode: {
    position: "absolute",
    zIndex: 2,
    width: 68,
    height: 68,
    display: "grid",
    placeItems: "center",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: "0.08em",
    color: designTokens.colors.white,
    background: designTokens.colors.blue,
    border: `1px solid ${designTokens.colors.blue}`,
    boxShadow: designTokens.shadows.blueGlow,
  },
  routeNodeSource: {
    left: 24,
    top: 76,
  },
  routeNodeEdge: {
    left: "calc(50% - 34px)",
    top: 26,
    background: "linear-gradient(135deg, rgba(76, 85, 255, 0.95), rgba(9, 12, 28, 0.92))",
  },
  routeNodeTarget: {
    right: 24,
    bottom: 34,
  },
  latencyGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    position: "relative",
    zIndex: 1,
  },
  latencyCard: {
    display: "grid",
    gap: 4,
    padding: 14,
    borderRadius: 18,
    background: "rgba(255, 255, 255, 0.045)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
  },
  latencyValue: {
    color: designTokens.colors.white,
    fontSize: "1.55rem",
    fontWeight: 950,
    letterSpacing: "-0.04em",
  },
  latencyLabel: {
    color: designTokens.colors.muted,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  metricStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 0,
    width: "min(1260px, calc(100% - 48px))",
    margin: "0 auto",
    borderTop: "1px solid #e2e8f0",
    borderBottom: "1px solid #e2e8f0",
  },
  metricStripCard: {
    display: "flex",
    gap: 14,
    alignItems: "center",
    padding: "24px 20px",
    background: "#ffffff",
    borderRight: "1px solid #e2e8f0",
  },
  metricStripValue: {
    color: "#087f5b",
    fontSize: "1.55rem",
    lineHeight: 1,
    letterSpacing: "-0.04em",
  },
  marketingSection: {
    display: "grid",
    gap: 38,
    width: "100%",
    marginTop: 72,
    padding: "82px max(24px, calc((100vw - 1260px) / 2))",
    background: "#f8fafc",
    borderTop: "1px solid #eef2f7",
    borderBottom: "1px solid #eef2f7",
  },
  sectionHeading: {
    display: "grid",
    gap: 12,
    maxWidth: 720,
    margin: "0 auto",
    textAlign: "center",
  },
  marketingSectionTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: "clamp(2rem, 4vw, 2.75rem)",
    fontWeight: 700,
    lineHeight: 1.2,
    letterSpacing: "-0.02em",
  },
  marketingSectionLead: {
    margin: 0,
    color: "#475569",
    fontSize: "1rem",
    lineHeight: 1.75,
  },
  showcaseGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 18,
  },
  showcaseCard: {
    display: "grid",
    gap: 12,
    padding: 24,
    borderRadius: 16,
    minHeight: 230,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "none",
  },
  signalBadge: {
    width: "fit-content",
    padding: "7px 10px",
    borderRadius: 999,
    background: "#ecfdf5",
    color: "#04775c",
    border: "1px solid #a7f3d0",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  showcaseTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: "1.25rem",
    letterSpacing: "-0.035em",
  },
  textAction: {
    width: "fit-content",
    alignSelf: "end",
    marginTop: "auto",
    padding: 0,
    border: "none",
    background: "transparent",
    color: "#087f5b",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  productSplit: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 0.9fr) minmax(420px, 1.1fr)",
    gap: 64,
    alignItems: "center",
    width: "min(1180px, calc(100% - 48px))",
    margin: "0 auto",
    padding: "96px 0",
    borderBottom: "1px solid #eef2f7",
  },
  productSplitCopy: {
    display: "grid",
    gap: 18,
  },
  checkList: {
    display: "grid",
    gap: 12,
    color: "#334155",
    fontSize: 14,
    fontWeight: 650,
  },
  analyticsPreviewCard: {
    display: "grid",
    gap: 18,
    padding: 28,
    borderRadius: 18,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 22px 60px rgba(15, 23, 42, 0.09)",
  },
  previewMetricRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  previewMetricValue: {
    display: "block",
    marginTop: 5,
    color: "#0f172a",
    fontSize: "2rem",
    letterSpacing: "-0.05em",
  },
  chartPreview: {
    height: 160,
    display: "flex",
    gap: 8,
    alignItems: "end",
    padding: 16,
    borderRadius: 22,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  chartBar: {
    flex: 1,
    minWidth: 8,
    borderRadius: "999px 999px 6px 6px",
    background: "linear-gradient(180deg, #34d399 0%, #087f5b 100%)",
    boxShadow: "0 8px 18px rgba(8, 127, 91, 0.18)",
  },
  apiPreviewCard: {
    display: "grid",
    gap: 16,
    padding: 24,
    borderRadius: 18,
    background: "#0f172a",
    border: "1px solid #1e293b",
    boxShadow: "0 24px 70px rgba(15, 23, 42, 0.18)",
  },
  codePanel: {
    display: "grid",
    gap: 6,
    padding: 18,
    borderRadius: 14,
    background: "#020617",
    border: "1px solid #1e293b",
    overflowX: "auto",
  },
  codeRow: {
    display: "block",
    color: designTokens.colors.ice,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    fontSize: 13,
    lineHeight: 1.6,
    whiteSpace: "pre",
  },
  trustGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
  },
  trustPill: {
    padding: "10px 13px",
    borderRadius: 999,
    color: "#d1fae5",
    background: "rgba(16, 185, 129, 0.12)",
    border: "1px solid rgba(52, 211, 153, 0.24)",
    fontSize: 13,
    fontWeight: 650,
  },
  textLink: {
    width: "fit-content",
    color: "#087f5b",
    fontSize: 15,
    fontWeight: 600,
    textDecoration: "none",
  },
  faqSection: {
    display: "grid",
    gap: 36,
    width: "min(980px, calc(100% - 48px))",
    margin: "0 auto",
    padding: "96px 0",
  },
  faqList: {
    display: "grid",
    gap: 12,
  },
  faqItem: {
    padding: "20px 22px",
    borderRadius: 14,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.04)",
  },
  faqQuestion: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: 750,
    cursor: "pointer",
  },
  faqAnswer: {
    margin: "14px 0 0",
    color: "#64748b",
    lineHeight: 1.7,
  },
  finalCta: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 24,
    alignItems: "center",
    width: "min(1180px, calc(100% - 48px))",
    margin: "0 auto 96px",
    padding: "48px",
    borderRadius: 22,
    background: "#0f172a",
    boxShadow: "0 24px 70px rgba(15, 23, 42, 0.18)",
  },
  finalCtaEyebrow: {
    margin: 0,
    color: "#6ee7b7",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  finalCtaTitle: {
    margin: "8px 0 10px",
    color: "#ffffff",
    fontSize: "clamp(2rem, 4vw, 3.35rem)",
    lineHeight: 1.1,
    letterSpacing: "-0.045em",
  },
  finalCtaText: {
    margin: 0,
    color: "#cbd5e1",
    lineHeight: 1.7,
  },
  finalCtaButton: {
    minHeight: 52,
    padding: "0 24px",
    border: "none",
    borderRadius: 10,
    background: "#087f5b",
    color: "#ffffff",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  featureCard: {
    padding: 18,
    borderRadius: 20,
    background: "rgba(15, 23, 42, 0.76)",
    border: "1px solid rgba(148, 163, 184, 0.12)",
  },
  featureTitle: {
    margin: "0 0 8px",
    fontSize: "1rem",
  },
  featureText: {
    margin: 0,
    color: "#64748b",
    lineHeight: 1.6,
  },
  pricingPreview: {
    display: "grid",
    gap: 16,
    padding: 22,
    borderRadius: 24,
    background: "rgba(15, 23, 42, 0.76)",
    border: "1px solid rgba(148, 163, 184, 0.12)",
  },
  publicFooter: {
    display: "grid",
    gridTemplateColumns: "minmax(260px, 1.5fr) repeat(2, minmax(150px, 0.6fr))",
    gap: "32px 56px",
    padding: "58px max(24px, calc((100vw - 1260px) / 2)) 28px",
    background: "#f8fafc",
    borderTop: "1px solid #e2e8f0",
  },
  publicFooterBrand: {
    display: "grid",
    gap: 14,
    maxWidth: 390,
    color: "#64748b",
    lineHeight: 1.65,
  },
  footerLogo: {
    width: 168,
  },
  publicFooterColumn: {
    display: "grid",
    alignContent: "start",
    gap: 12,
    color: "#64748b",
    fontSize: 14,
  },
  publicFooterBottom: {
    gridColumn: "1 / -1",
    display: "flex",
    justifyContent: "space-between",
    gap: 20,
    paddingTop: 26,
    color: "#64748b",
    borderTop: "1px solid #e2e8f0",
    fontSize: 13,
  },
  authCard: {
    position: "sticky",
    top: 22,
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: designTokens.shadows.panel,
  },
  authTabs: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    borderBottom: `1px solid ${designTokens.colors.border}`,
  },
  authTab: {
    border: "none",
    background: "transparent",
    color: designTokens.colors.text,
    padding: "16px 18px",
    fontWeight: 700,
    cursor: "pointer",
  },
  authTabActive: {
    border: "none",
    background: "#eef3ff",
    color: designTokens.colors.blue,
    padding: "16px 18px",
    fontWeight: 800,
    cursor: "pointer",
  },
  authBody: {
    display: "grid",
    gap: 18,
    width: "100%",
    maxWidth: 500,
    padding: "24px 48px",
    border: "1px solid rgba(15, 23, 42, 0.05)",
    borderRadius: 16,
    background: "rgba(255, 255, 255, 0.95)",
  },
  authLogo: {
    width: 62,
    height: 62,
  },
  authTitle: {
    margin: 0,
    color: "#04775c",
    fontSize: 20,
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: "-0.01em",
  },
  authSubtitle: {
    margin: "10px 0 0",
    color: "#475569",
    fontSize: 14,
    lineHeight: 1.6,
  },
  authPageHeader: {
    minHeight: 70,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    padding: "10px 24px",
    background: "#ffffff",
    borderBottom: "1px solid #e2e8f0",
  },
  authHeaderSwitch: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    color: "#64748b",
    fontSize: 14,
  },
  authHeaderButton: {
    minHeight: 40,
    padding: "0 16px",
    borderRadius: 10,
    border: "1px solid #e0e0e0",
    background: "#ffffff",
    color: "#1e293b",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
  },
  authPageMain: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(520px, 1fr)",
    minHeight: "calc(100vh - 140px)",
    background: "#f7f8fb",
  },
  authFormPane: {
    display: "grid",
    justifyItems: "center",
    alignContent: "start",
    padding: "clamp(56px, 8vw, 112px) 36px",
    background: "#f7f8fb",
  },
  authSubmitButton: {
    minHeight: 40,
    border: "none",
    borderRadius: 12,
    padding: "0 16px",
    background: "#04775c",
    color: "#ffffff",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    boxShadow: "none",
  },
  authSecurityNote: {
    margin: 0,
    padding: "12px 14px",
    borderRadius: 10,
    color: "#475569",
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    fontSize: 12,
    lineHeight: 1.5,
    textAlign: "center",
  },
  authInlineSwitch: {
    margin: 0,
    color: "#475569",
    fontSize: 14,
    textAlign: "center",
  },
  inlineTextButton: {
    padding: 0,
    border: "none",
    background: "transparent",
    color: "#04775c",
    fontWeight: 600,
    cursor: "pointer",
  },
  authVisualPane: {
    display: "grid",
    alignContent: "center",
    gap: 28,
    padding: "56px clamp(36px, 6vw, 88px)",
    background: "linear-gradient(145deg, #ecfdf5 0%, #f0fdfa 44%, #eff6ff 100%)",
    borderLeft: "1px solid #dbeafe",
  },
  authVisualCopy: {
    display: "grid",
    gap: 14,
    maxWidth: 580,
  },
  authVisualTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: "clamp(2rem, 3.5vw, 3.4rem)",
    lineHeight: 1.08,
    letterSpacing: "-0.045em",
  },
  authVisualText: {
    margin: 0,
    color: "#475569",
    lineHeight: 1.7,
  },
  authVisualStats: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 12,
  },
  authFooter: {
    minHeight: 70,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
    padding: "20px 24px",
    color: "#64748b",
    background: "#ffffff",
    borderTop: "1px solid #e2e8f0",
    fontSize: 12,
  },
  authFooterLinks: {
    display: "flex",
    alignItems: "center",
    gap: 18,
  },
  headerBar: {
    gridColumn: "1 / -1",
    position: "sticky",
    top: 16,
    zIndex: 1000,
    display: "flex",
    justifyContent: "space-between",
    gap: 20,
    alignItems: "center",
    flexWrap: "wrap",
    padding: "18px 22px",
    borderRadius: 20,
    background: "rgba(255, 255, 255, 0.88)",
    border: "1px solid rgba(226, 232, 240, 0.88)",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05), 0 4px 12px rgba(0, 0, 0, 0.03)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  dashboardBrandBlock: {
    display: "flex",
    gap: 16,
    alignItems: "center",
    minWidth: 0,
    flex: "1 1 560px",
  },
  dashboardLogo: {
    width: 164,
    height: 44,
    flex: "0 0 auto",
  },
  headerDivider: {
    width: 1,
    height: 46,
    background: "var(--sl-surface-border)",
    flex: "0 0 auto",
  },
  workspaceHeadingBlock: {
    minWidth: 0,
  },
  dashboardTitle: {
    margin: "4px 0 0",
    fontSize: "clamp(1.55rem, 2.2vw, 2.35rem)",
    lineHeight: 1.05,
    letterSpacing: "-0.035em",
    color: designTokens.colors.ink,
  },
  workspaceMeta: {
    margin: "6px 0 0",
    color: designTokens.colors.text,
    fontSize: 13,
    lineHeight: 1.45,
  },
  headerActions: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    flex: "0 1 520px",
    justifyContent: "flex-end",
    minWidth: 0,
  },
  navActionButton: {
    border: "1px solid transparent",
    borderRadius: 10,
    padding: "9px 12px",
    minHeight: 40,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "none",
    transition: "transform 180ms ease, filter 180ms ease, box-shadow 180ms ease",
  },
  dashboardGrid: {
    gridColumn: 2,
    gridRow: 3,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.42fr) minmax(320px, 0.78fr)",
    gridTemplateAreas:
      '"builder links" "analytics analytics" "domains domains" "billing billing" "docs docs"',
    gap: 24,
    alignItems: "start",
  },
  dashboardNavCard: {
    gridColumn: 1,
    gridRow: "2 / span 2",
    display: "grid",
    gap: 18,
    padding: 16,
    borderRadius: 24,
    position: "sticky",
    top: 18,
    zIndex: 6,
    boxShadow: designTokens.shadows.panel,
  },
  dashboardNavIntro: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    padding: "5px 5px 13px",
    borderBottom: "1px solid var(--sl-surface-border)",
  },
  workspaceAvatar: {
    width: 44,
    height: 44,
    display: "grid",
    placeItems: "center",
    borderRadius: 14,
    color: "#ffffff",
    background: "#04775c",
    boxShadow: "none",
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: "0.05em",
  },
  navWorkspaceCopy: {
    minWidth: 0,
    display: "grid",
    gap: 2,
  },
  navWorkspaceName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 13,
  },
  navWorkspaceSlug: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--sl-muted-content)",
    fontSize: 11,
  },
  dashboardNavItems: {
    display: "grid",
    gap: 7,
  },
  dashboardNavItem: {
    width: "100%",
    display: "flex",
    gap: 11,
    alignItems: "center",
    border: "1px solid transparent",
    borderRadius: 13,
    padding: "11px 12px",
    background: "transparent",
    color: "var(--sl-content)",
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: "nowrap",
    cursor: "pointer",
    textAlign: "left",
    transition: "background 180ms ease, border-color 180ms ease, color 180ms ease",
  },
  dashboardNavIndex: {
    width: 28,
    height: 28,
    display: "grid",
    placeItems: "center",
    borderRadius: 9,
    color: designTokens.colors.green,
    background: "#ecfdf5",
    fontSize: 10,
    fontWeight: 700,
  },
  dashboardNavPlan: {
    display: "grid",
    gap: 4,
    padding: 18,
    borderRadius: 18,
    color: "#064e3b",
    background: "#ecfdf5",
    border: "1px solid #a7f3d0",
    boxShadow: "none",
  },
  navPlanLabel: {
    margin: 0,
    color: "#04775c",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  navPlanValue: {
    marginTop: 8,
    color: "#064e3b",
    fontSize: "2rem",
    lineHeight: 1,
  },
  navPlanHint: {
    color: "#04775c",
    fontSize: 11,
  },
  navPlanButton: {
    marginTop: 10,
    border: "none",
    borderRadius: 12,
    padding: "11px 14px",
    color: "#ffffff",
    background: "#04775c",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  linkBuilderForm: {
    display: "grid",
    gap: 18,
  },
  builderFormGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  analyticsDetailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 18,
  },
  billingOverviewGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 14,
  },
  billingDetailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 14,
  },
  commandStrip: {
    gridColumn: 2,
    gridRow: 2,
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 14,
    padding: 30,
    borderRadius: 30,
    overflow: "hidden",
    background: "#0b1736",
    boxShadow: "0 28px 80px rgba(11, 23, 54, 0.2)",
  },
  commandStripHeading: {
    gridColumn: "1 / -1",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "end",
    gap: 14,
    marginBottom: 2,
  },
  overviewTitle: {
    margin: "3px 0 0",
    color: "#ffffff",
    fontSize: "clamp(1.8rem, 3vw, 2.8rem)",
    lineHeight: 1.08,
    letterSpacing: "-0.045em",
  },
  overviewTimestamp: {
    color: "var(--sl-muted-content)",
    fontSize: 11,
  },
  commandCard: {
    display: "grid",
    gap: 11,
    padding: 20,
    borderRadius: 20,
    background: "rgba(255, 255, 255, 0.09)",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.08)",
  },
  commandValue: {
    color: "#ffffff",
    fontSize: "2.15rem",
    lineHeight: 1,
    letterSpacing: "-0.04em",
  },
  commandCardTop: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  commandIndex: {
    color: designTokens.colors.blue,
    fontSize: 10,
    fontWeight: 900,
  },
  sidebarCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 12,
    padding: 20,
    display: "grid",
    gap: 16,
  },
  builderCard: {
    background: "#ffffff",
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 28,
    padding: 30,
    display: "grid",
    gap: 18,
    boxShadow: designTokens.shadows.panel,
  },
  analyticsPanel: {
    display: "grid",
    gap: 18,
    alignContent: "start",
    padding: 30,
    borderRadius: 28,
    border: "1px solid var(--sl-surface-border)",
    boxShadow: designTokens.shadows.panel,
  },
  analyticsHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  sectionEyebrow: {
    margin: 0,
    fontSize: 12,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: designTokens.colors.blue,
    fontWeight: 900,
  },
  panelTitle: {
    margin: "6px 0 0",
    fontSize: "clamp(1.35rem, 2vw, 1.75rem)",
    letterSpacing: "-0.035em",
    color: designTokens.colors.ink,
  },
  panelLead: {
    margin: "7px 0 0",
    color: "var(--sl-muted-content)",
    fontSize: 13,
    lineHeight: 1.5,
  },
  panelTitleRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  label: {
    display: "grid",
    gap: 10,
    fontSize: 14,
    fontWeight: 700,
    color: designTokens.colors.ink,
  },
  input: {
    width: "100%",
    borderRadius: 14,
    border: `1px solid ${designTokens.colors.border}`,
    background: "#f8faf8",
    color: designTokens.colors.ink,
    minHeight: 50,
    padding: "0 16px",
    outline: "none",
    fontSize: 14,
    transition: "border-color 180ms ease, box-shadow 180ms ease, background 180ms ease",
  },
  aliasInputGroup: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    alignItems: "stretch",
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 14,
    overflow: "hidden",
    background: "#ffffff",
  },
  aliasPrefix: {
    display: "flex",
    alignItems: "center",
    padding: "0 14px",
    background: "#eef3ff",
    color: designTokens.colors.blue,
    borderRight: `1px solid ${designTokens.colors.border}`,
    fontWeight: 900,
    fontSize: 14,
    whiteSpace: "nowrap",
  },
  aliasInput: {
    border: "none",
    borderRadius: 0,
    boxShadow: "none",
  },
  textarea: {
    width: "100%",
    minHeight: 110,
    resize: "vertical",
    borderRadius: 14,
    border: `1px solid ${designTokens.colors.border}`,
    background: "#f8faf8",
    color: designTokens.colors.ink,
    padding: "15px 16px",
    outline: "none",
    fontSize: 14,
    fontFamily: "inherit",
    transition: "border-color 180ms ease, box-shadow 180ms ease, background 180ms ease",
  },
  select: {
    width: "100%",
    borderRadius: 14,
    border: `1px solid ${designTokens.colors.border}`,
    background: "#f8faf8",
    color: designTokens.colors.ink,
    minHeight: 50,
    padding: "0 16px",
    outline: "none",
    fontSize: 14,
  },
  primaryButton: {
    border: "none",
    borderRadius: 12,
    minHeight: 46,
    padding: "0 20px",
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: 0,
    background: designTokens.colors.green,
    color: "#ffffff",
    cursor: "pointer",
    boxShadow: "none",
    transition: "transform 180ms ease, background 180ms ease",
  },
  secondaryButton: {
    border: `1px solid ${designTokens.colors.border}`,
    borderRadius: 12,
    minHeight: 46,
    padding: "0 18px",
    fontSize: 14,
    fontWeight: 500,
    background: "#ffffff",
    color: "#1e293b",
    cursor: "pointer",
    transition: "transform 180ms ease, border-color 180ms ease, background 180ms ease",
  },
  dangerButton: {
    border: "none",
    borderRadius: 12,
    minHeight: 46,
    padding: "0 18px",
    fontSize: 14,
    fontWeight: 600,
    background: designTokens.colors.danger,
    color: "#fff7ed",
    cursor: "pointer",
  },
  feedback: {
    margin: 0,
    padding: "12px 14px",
    borderRadius: 8,
    lineHeight: 1.5,
    fontSize: 14,
    fontWeight: 700,
  },
  feedbackError: {
    color: "#912018",
    background: "#fee4e2",
    border: "1px solid #fecdca",
  },
  feedbackSuccess: {
    color: "#05603a",
    background: "#dcf8ee",
    border: "1px solid #a6f4d0",
  },
  helperText: {
    margin: 0,
    color: designTokens.colors.text,
    lineHeight: 1.6,
  },
  miniHelperText: {
    margin: "6px 0 0",
    color: designTokens.colors.muted,
    fontSize: 12,
    lineHeight: 1.4,
  },
  optionalLabel: {
    width: "fit-content",
    padding: "3px 7px",
    borderRadius: 999,
    color: "var(--sl-muted-content)",
    background: "var(--sl-surface-accent)",
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  inlineFieldLabel: {
    display: "grid",
    gap: 8,
    minWidth: 0,
    color: "var(--sl-heading)",
    fontSize: 13,
    fontWeight: 750,
  },
  legalCard: {
    display: "grid",
    gap: 16,
    padding: 22,
    borderRadius: 24,
    background: "rgba(6, 78, 59, 0.24)",
    border: "1px solid rgba(45, 212, 191, 0.18)",
  },
  legalList: {
    display: "grid",
    gap: 10,
  },
  legalNoticeItem: {
    margin: 0,
    color: "#d1fae5",
    lineHeight: 1.65,
  },
  legalFinePrint: {
    margin: 0,
    color: "#a7f3d0",
    fontSize: 13,
    lineHeight: 1.6,
  },
  legalLinkRow: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap",
  },
  consentBox: {
    display: "grid",
    gap: 12,
    padding: 18,
    borderRadius: 20,
    background: "#f0f7f3",
    border: "1px solid var(--sl-surface-border)",
  },
  consentIntro: {
    margin: 0,
    color: "var(--sl-content)",
    fontSize: 13,
    lineHeight: 1.6,
  },
  checkboxRow: {
    display: "grid",
    gridTemplateColumns: "20px minmax(0, 1fr)",
    gap: 10,
    alignItems: "start",
    color: "var(--sl-content)",
    fontSize: 13,
    lineHeight: 1.5,
    cursor: "pointer",
  },
  checkboxInput: {
    width: 16,
    height: 16,
    marginTop: 2,
    accentColor: designTokens.colors.blue,
  },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 14,
  },
  metricCard: {
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
    borderRadius: 20,
    padding: 20,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  metricLabel: {
    margin: 0,
    color: designTokens.colors.muted,
    fontSize: 13,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    fontWeight: 800,
  },
  metricValue: {
    margin: "12px 0 0",
    fontSize: "2.2rem",
    fontWeight: 900,
    lineHeight: 1,
    color: "var(--sl-heading)",
  },
  metricValueSmall: {
    margin: "12px 0 0",
    fontSize: "1rem",
    fontWeight: 700,
    lineHeight: 1.5,
  },
  metricHint: {
    color: designTokens.colors.muted,
    fontSize: 13,
  },
  resultCard: {
    display: "grid",
    gap: 18,
    padding: 22,
    borderRadius: 22,
    background: "#f0f7f3",
    border: "1px solid var(--sl-surface-border)",
  },
  resultTopRow: {
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  mutedLabel: {
    margin: "0 0 8px",
    fontSize: 12,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: designTokens.colors.muted,
  },
  link: {
    color: designTokens.colors.cyan,
    fontWeight: 700,
    textDecoration: "none",
    wordBreak: "break-all",
  },
  inlineActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  inlineForm: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 10,
    alignItems: "center",
  },
  qrPanel: {
    display: "flex",
    gap: 18,
    alignItems: "center",
    flexWrap: "wrap",
  },
  qrText: {
    flex: 1,
    minWidth: 220,
  },
  qrHeadline: {
    margin: "0 0 6px",
    fontSize: "1.05rem",
    fontWeight: 800,
  },
  qrDescription: {
    margin: "0 0 14px",
    color: "var(--sl-content)",
    lineHeight: 1.6,
  },
  linkList: {
    display: "grid",
    gap: 10,
    maxHeight: 690,
    overflowY: "auto",
    paddingRight: 3,
  },
  linkListItem: {
    border: "1px solid var(--sl-surface-border)",
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    color: designTokens.colors.ink,
    padding: 16,
    textAlign: "left",
    cursor: "pointer",
    transition: "transform 180ms ease, border-color 180ms ease, background 180ms ease",
  },
  linkListItemActive: {
    border: `1px solid ${designTokens.colors.blue}`,
    borderRadius: 18,
    background: "var(--sl-surface-accent)",
    color: designTokens.colors.ink,
    padding: 16,
    textAlign: "left",
    cursor: "pointer",
    boxShadow: designTokens.shadows.blueGlow,
  },
  linkListTopRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
  },
  linkShortCode: {
    fontWeight: 800,
    fontSize: 15,
    letterSpacing: "0.03em",
  },
  linkOriginal: {
    margin: "10px 0",
    color: "var(--sl-content)",
    lineHeight: 1.55,
    wordBreak: "break-word",
  },
  linkListFooter: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    color: "var(--sl-muted-content)",
    fontSize: 12,
    flexWrap: "wrap",
  },
  panelCard: {
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
    borderRadius: 28,
    padding: 28,
    display: "grid",
    gap: 16,
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  linksPanel: {
    alignSelf: "start",
    minWidth: 0,
  },
  docsQuickPanel: {
    display: "grid",
    gap: 14,
    padding: 28,
    borderRadius: 28,
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
  },
  docsQuickList: {
    display: "grid",
    gap: 10,
  },
  docsQuickItem: {
    display: "grid",
    gap: 5,
    padding: 12,
    borderRadius: 14,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
    color: designTokens.colors.text,
    fontSize: 13,
    lineHeight: 1.45,
  },
  subscriptionCard: {
    display: "grid",
    gap: 10,
    padding: 20,
    borderRadius: 22,
    background: "var(--sl-surface-accent)",
    border: "1px solid var(--sl-surface-border)",
  },
  subscriptionTitle: {
    margin: 0,
    color: "var(--sl-heading)",
    fontSize: "1.65rem",
    lineHeight: 1,
    fontWeight: 950,
  },
  billingStatsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
  },
  billingStatCard: {
    padding: 18,
    borderRadius: 20,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  billingStatLabel: {
    margin: 0,
    color: designTokens.colors.muted,
    fontSize: 12,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  billingStatValue: {
    margin: "10px 0 0",
    fontSize: "1.35rem",
    fontWeight: 800,
    lineHeight: 1.2,
  },
  billingStatValueSmall: {
    margin: "10px 0 0",
    fontSize: "0.95rem",
    fontWeight: 700,
    lineHeight: 1.5,
  },
  planGrid: {
    display: "grid",
    gap: 12,
  },
  compactPlanGrid: {
    display: "grid",
    gap: 10,
  },
  planCard: {
    display: "grid",
    gap: 14,
    padding: 18,
    borderRadius: 16,
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
    boxShadow: "none",
  },
  compactPlanCard: {
    display: "grid",
    gap: 10,
    padding: 18,
    borderRadius: 20,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  planCardFeatured: {
    border: `1px solid ${designTokens.colors.borderBright}`,
    boxShadow: "0 0 0 1px rgba(4, 119, 92, 0.08)",
  },
  planHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  planName: {
    fontSize: "1rem",
  },
  planPrice: {
    margin: 0,
    fontSize: "1.7rem",
    fontWeight: 900,
    lineHeight: 1,
    color: "var(--sl-heading)",
  },
  compactPlanPrice: {
    margin: 0,
    fontSize: "1.25rem",
    fontWeight: 900,
    lineHeight: 1.1,
    color: "var(--sl-heading)",
  },
  planFeatureList: {
    display: "grid",
    gap: 8,
  },
  planFeatureItem: {
    margin: 0,
    color: designTokens.colors.text,
    lineHeight: 1.5,
  },
  paymentCard: {
    display: "grid",
    gap: 8,
    padding: 20,
    borderRadius: 22,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  usageGrid: {
    display: "grid",
    gap: 12,
  },
  usageBar: {
    display: "grid",
    gap: 8,
  },
  usageBarHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  usageBarLabel: {
    color: designTokens.colors.text,
    fontSize: 13,
    fontWeight: 800,
  },
  usageBarCount: {
    color: designTokens.colors.muted,
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  usageBarTrack: {
    height: 8,
    borderRadius: 999,
    background: "rgba(148, 163, 184, 0.16)",
    overflow: "hidden",
  },
  usageBarFill: {
    height: "100%",
    borderRadius: 999,
    transition: "width 180ms ease",
  },
  invoiceList: {
    display: "grid",
    gap: 10,
  },
  invoiceRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    padding: 12,
    borderRadius: 14,
    background: "var(--sl-surface)",
    border: "1px solid var(--sl-surface-border)",
  },
  inlineLink: {
    color: designTokens.colors.blue,
    fontSize: 13,
    fontWeight: 800,
    textDecoration: "none",
  },
  domainList: {
    display: "grid",
    gap: 12,
  },
  domainCard: {
    display: "grid",
    gap: 12,
    padding: 20,
    borderRadius: 22,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  dnsGrid: {
    display: "grid",
    gap: 10,
  },
  codeLine: {
    margin: "4px 0 0",
    padding: "8px 10px",
    borderRadius: 10,
    background: "rgba(0, 0, 0, 0.42)",
    color: designTokens.colors.ice,
    fontFamily: "ui-monospace, SFMono-Regular, Consolas, monospace",
    fontSize: 12,
    lineHeight: 1.5,
    wordBreak: "break-all",
  },
  routeList: {
    display: "grid",
    gap: 12,
  },
  routeCard: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    flexWrap: "wrap",
    padding: 18,
    borderRadius: 20,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  routeLabel: {
    margin: "0 0 6px",
    fontSize: 13,
    fontWeight: 800,
    color: "var(--sl-heading)",
    letterSpacing: "0.03em",
    textTransform: "uppercase",
  },
  routeUrl: {
    margin: 0,
    color: "var(--sl-content)",
    wordBreak: "break-all",
  },
  routeMeta: {
    display: "grid",
    gap: 8,
    justifyItems: "end",
  },
  routeTime: {
    fontSize: 12,
    color: "var(--sl-muted-content)",
  },
  deviceBar: {
    display: "grid",
    gap: 8,
  },
  deviceBarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deviceBarLabel: {
    fontWeight: 700,
    textTransform: "capitalize",
  },
  deviceBarCount: {
    color: "var(--sl-content)",
  },
  deviceBarTrack: {
    height: 10,
    borderRadius: 999,
    background: "rgba(100, 116, 139, 0.18)",
    overflow: "hidden",
  },
  deviceBarFill: {
    height: "100%",
    borderRadius: 999,
    background: "linear-gradient(90deg, #ffffff 0%, #4c55ff 70%, #79e6ff 100%)",
    boxShadow: "0 0 18px rgba(76, 85, 255, 0.35)",
  },
  eventList: {
    display: "grid",
    gap: 12,
  },
  eventCard: {
    padding: 16,
    borderRadius: 18,
    background: "var(--sl-surface-soft)",
    border: "1px solid var(--sl-surface-border)",
  },
  eventTopRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  eventTitle: {
    fontSize: 15,
  },
  eventMeta: {
    margin: "8px 0 6px",
    color: "var(--sl-content)",
  },
  eventTarget: {
    margin: "0 0 6px",
    color: designTokens.colors.blue,
    wordBreak: "break-all",
  },
  eventReferrer: {
    margin: 0,
    color: "var(--sl-muted-content)",
    wordBreak: "break-word",
  },
  emptyState: {
    margin: 0,
    color: "var(--sl-muted-content)",
    lineHeight: 1.6,
  },
};

export { designTokens, enterpriseDashboardStyles, styles };
